### PR TITLE
TASK: Improve text formatting

### PR DESCRIPTION
**Pull request by alexander-nitsche**
Hi Karsten,

this PR is about beautifying the post in the Slack channel. The first result yesterday was missing some formatting. This patch converts some HTML tags to Slack's Markdown. To take the script to the *next level*, I added tests including Composer setup, but in a way that doesn't require any changes to the Jenkins production setup.

The tests and post formatting have been carefully checked.

Greetings
Alex

### CODE REVIEW

**Comment by alexander-nitsche** [comment]
Before:
Screenshot from 2023-01-20 22-09-33

After:
Screenshot from 2023-01-20 22-10-39

**Comment by alexander-nitsche** [comment]
Screenshot from 2023-01-24 10-07-55
Done :)

**Comment by alexander-nitsche** [comment]
Switched to the latest "block" Slack message structure to be able to apply the author's name to the author's icon. With this structure, the message now has a slightly different look:
stackoverflow-connector-with-block-structure
and expanded:
stackoverflow-connector-with-block-structure-expanded

**Review by kdambekalns — APPROVED** [review]
Looks good by reading

**Pull request merged**
